Numpy:数値演算ライブラリ。高次元配列の取り扱いに長けているので、画像処理、機械学習などに応用されている。

# Table of Contents
## 1. 配列の基本
* 1.1. np.array
* 1.2. np.arrayの属性

## 2. 配列の作成
* 2.1. 0と1
* 2.2. 連続数
* 2.3. 等間隔

## 3. 配列の操作
* 3.1. indexing(データ選択)
* 3.2. 条件によるindexing
* 3.3. 配列の変形、結合

## 4. 演算
* 4.1. 基本演算
* 4.2. 内積・外積・直積
* 4.3. 線形代数の基礎演算

In [1]:
import numpy as np

# 1. 配列の基本

## 1.1. np.array

In [3]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])
type(a)

numpy.ndarray

## 1.2. np.arrayの属性

- レイアウトの確認

ndarray.shape	配列の形状

ndarray.ndim	配列の次元

ndarray.size	配列の要素数

ndarray.dtype   要素の型

ndarray.nbytes	配列によって消費されている容量

- 特殊操作

ndarray.T 転置

ndarray.flat	一次元(ベクトル)をiteratorとして返す

ndarray.real	real part

ndarray.imag	imaginary part

詳しくは、https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [7]:
#要素の数
a.size

15

In [8]:
a.dtype

dtype('int64')

In [9]:
a.nbytes

120

In [11]:
a = np.array(a, dtype=np.int32)
a.nbytes

60

In [12]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]], dtype=int32)

In [13]:
a.flat


In [14]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [15]:
a.real

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)

In [16]:
a.imag

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [17]:
b = np.array([1+1j, 2, 3],dtype=complex)

In [18]:
b.imag

array([1., 0., 0.])

In [19]:
b.real

array([1., 2., 3.])

In [20]:
b

array([1.+1.j, 2.+0.j, 3.+0.j])

# 2. 配列の作成

## 2.1. 0と1

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.ones((2,2,2), dtype=np.float32)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [31]:
np.empty((2,2))

array([[0.0078125, 0.0078125],
       [0.0078125, 0.0078125]])

## 2.2. 連続数

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## 2.3. 等間隔

In [39]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

# 3. 配列の操作

## 3.1. indexing(データの指定方法)

In [66]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
a[0]

array([0, 1, 2, 3, 4])

In [75]:
a[0][1:3]

array([1, 2])

In [76]:
# N間隔で取得する

In [80]:
a[0][::2]

array([0, 2, 4])

In [81]:
# 逆順で取得する

In [83]:
a[0][5:0:-1]

array([4, 3, 2, 1])

In [84]:
# 後ろからN番目

In [88]:
a[0][-2:]

array([3, 4])

### 3.2. 条件によるindexing

In [89]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])

In [90]:
#0, 1, 1行目, 0, 1, 0行目
a[[0, 1, 1],[0, 1, 0]]

array([0, 6, 5])

### 条件によるindexing

In [94]:
a_rowsum = a.sum(-1, keepdims=True)

In [95]:
a_rowsum

array([[10],
       [35],
       [60]])

In [97]:
bool_ = a_rowsum > 30

In [99]:
a_rowsum[bool_]

array([35, 60])

## 3.3. 配列の変形、結合

In [101]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [103]:
l = np.arange(0,100,1)

In [104]:
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [109]:
l.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [110]:
l.resize((10,10))

In [111]:
l

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
# -1で次元を自動補完
l.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
#縦方向に結合
np.vstack((l, l))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [119]:
#横方向に結合
np.hstack((l,l))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

# 4. 演算

## 4.1. 基本演算

In [120]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
a + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [122]:
a*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [123]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [127]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [128]:
np.cos([3.14])

array([-0.99999873])

In [129]:
a<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

## 4.2. 内積、外積、直積

In [131]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [133]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [134]:
0 + 1 + 4 + 9 + 16

30

In [135]:
#内積
np.dot(a, a.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [136]:
#外積(クロス積)
np.cross([1,0, 0], [0,1,0])

array([0, 0, 1])

In [137]:
#直積
np.outer([1,2,3], [1,2,3])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [139]:
#要素同士を掛け合わせる
np.array([1,2,3])*np.array([1,2,3])

array([1, 4, 9])

## 4.3. 線形代数の基礎演算

In [140]:
# 転置
a.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [141]:
# 逆行列
a = np.random.randint(1,10,(3,3))
a

array([[1, 1, 3],
       [9, 2, 1],
       [3, 7, 2]])

In [142]:
a_inv = np.linalg.inv(a)
print(a_inv)

[[-0.01960784  0.12418301 -0.03267974]
 [-0.09803922 -0.04575163  0.16993464]
 [ 0.37254902 -0.02614379 -0.04575163]]


In [143]:
np.dot(a,a_inv)

array([[ 1.00000000e+00,  1.73472348e-17, -2.08166817e-17],
       [ 0.00000000e+00,  1.00000000e+00, -6.93889390e-18],
       [ 0.00000000e+00, -6.93889390e-18,  1.00000000e+00]])

In [146]:
#連立方程式の解
np.linalg.solve(a, [1,2,3])

array([0.13071895, 0.32026144, 0.18300654])

In [147]:
#固有値、固有ベクトル
a= np.array([[1,2],[5,6]])
eigenvalues, eigen_vectors = np.linalg.eig(a)
eigenvalues, eigen_vectors

(array([-0.53112887,  7.53112887]), array([[-0.79402877, -0.2928046 ],
        [ 0.60788018, -0.9561723 ]]))

In [148]:
#行列式の値
np.linalg.det(a)

-3.999999999999999