Numpy:数値演算ライブラリ。高次元配列の取り扱いに長けているので、画像処理、機械学習などに応用されている。

# Table of Contents
## 1. 配列の基本
* 1.1. np.array
* 1.2. np.arrayの属性

## 2. 配列の作成
* 2.1. 0と1
* 2.2. 連続数
* 2.3. 等間隔

## 3. 配列の操作
* 3.1. indexing(データ選択)
* 3.2. 条件によるindexing
* 3.3. 配列の変形、結合

## 4. 演算
* 4.1. 基本演算
* 4.2. 内積・外積・直積
* 4.3. 線形代数の基礎演算

In [1]:
import numpy as np

# 1. 配列の基本

## 1.1. np.array

In [3]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])
type(a)

numpy.ndarray

## 1.2. np.arrayの属性

- レイアウトの確認

ndarray.shape	配列の形状

ndarray.ndim	配列の次元

ndarray.size	配列の要素数

ndarray.dtype   要素の型

ndarray.nbytes	配列によって消費されている容量

- 特殊操作

ndarray.T 転置

ndarray.flat	一次元(ベクトル)をiteratorとして返す

ndarray.real	real part

ndarray.imag	imaginary part

詳しくは、https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

# 2. 配列の作成

## 2.1. 0と1

## 2.2. 連続数

## 2.3. 等間隔

# 3. 配列の操作

## 3.1. indexing(データの指定方法)

In [1]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])
a

NameError: name 'np' is not defined

### 3.2. 条件によるindexing

In [89]:
a = np.array([[ 0,  1,  2,  3,  4],
                 [ 5,  6,  7,  8,  9],
                 [10, 11, 12, 13, 14]])

In [90]:
#0, 1, 1行目, 0, 1, 0行目
a[[0, 1, 1],[0, 1, 0]]

array([0, 6, 5])

### 条件によるindexing

## 3.3. 配列の変形、結合

# 4. 演算

## 4.1. 基本演算

In [120]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 4.2. 内積、外積、直積

In [131]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 4.3. 線形代数の基礎演算

In [140]:
# 転置
a.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])