# TensorFlow 2.0

## 課題
    1. データの数を100,000にしてみましょう
    2. 学習率を変えてみましょう. 
    3. 損失関数をHuber lossに変えてみましょう 
    huber lossを適用するための文法は'huber_loss'です。
    
## 解答

今回はそれぞれの値を変更するだけですので、解答を記載したコードは作成しません。

## ライブラリのインポート

In [1]:
# We must always import the relevant libraries for our problem at hand. NumPy and TensorFlow are required for this example.
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## データの作成

In [2]:
# データの数を宣言します
observations = 100000

# uniformメソッドを使ってランダムなデータを作成します
xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

# column_stackを使って二つのベクトルを行列にします
generated_inputs = np.column_stack((xs,zs))

# ノイズを足します
noise = np.random.uniform(-1, 1, (observations,1))

# Produce the targets according to our f(x,z) = 2x - 3z + 5 + noise definition.
# In this way, we are basically saying: the weights should be 2 and -3, while the bias is 5.
generated_targets = 2*xs - 3*zs + 5 + noise

# save into an npz file called "TF_intro"
np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

## TensorFlowを用いたコードの作成

In [3]:
# NPZ形式のファイルの読み込み
training_data = np.load('TF_intro.npz')

In [5]:
# 入力のサイズの定義
input_size = 2
# 出力のサイズの定義
output_size = 1

# モデルの作成
model = tf.keras.Sequential([
                            # 'Dense'メソッドで線形結合を行っていきます
                            tf.keras.layers.Dense(output_size,
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                                 )
                            ])

# 今回はcustom optimizerを使って学習率を0.2に設定します
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.2)

# 'compile'で最適化アルゴリズムと損失関数を指定していきます
model.compile(optimizer=custom_optimizer, loss='huber_loss')

# データをモデルにフィットさせていきます
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)

Train on 100000 samples
Epoch 1/100
100000/100000 - 3s - loss: 1.9906
Epoch 2/100
100000/100000 - 3s - loss: 1.9765
Epoch 3/100
100000/100000 - 3s - loss: 1.9650
Epoch 4/100
100000/100000 - 3s - loss: 1.9679
Epoch 5/100
100000/100000 - 3s - loss: 1.9697
Epoch 6/100


KeyboardInterrupt: 

## 重みとバイアスの抽出


In [5]:
# 重みとバイアスを表示します
model.layers[0].get_weights()

[array([[ 1.9776261],
        [-2.9764102]], dtype=float32), array([4.975083], dtype=float32)]

In [6]:
# 変数に入れます
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.9776261],
       [-2.9764102]], dtype=float32)

In [7]:
# 変数に入れます
bias = model.layers[0].get_weights()[1]
bias

array([4.975083], dtype=float32)

## 出力の抽出

In [8]:
# 入力データに対する予測の値を表示していきます
model.predict_on_batch(training_data['inputs']).round(1)

array([[ -9.8],
       [  9.9],
       [ -6. ],
       [ 17.9],
       [  4.5],
       [ 22.8],
       [  2.5],
       [-10.9],
       [ 19.4],
       [-10. ],
       [ 34.2],
       [  6.4],
       [-26.7],
       [-27.8],
       [ -7.8],
       [ 17.1],
       [ 27.4],
       [ 15.3],
       [-15. ],
       [-21.2],
       [  9.4],
       [-19.3],
       [ 14.5],
       [ 26.3],
       [ 21.9],
       [ -0.3],
       [ -7.9],
       [ 28.2],
       [  1.7],
       [-14.2],
       [ 13.1],
       [ 11.5],
       [ -1.2],
       [ 25.2],
       [  0.3],
       [  6.6],
       [ -6. ],
       [ 17.6],
       [ 12.7],
       [  8.3],
       [ -7.8],
       [ 25. ],
       [ -3.8],
       [ 10.5],
       [  8. ],
       [ 12.3],
       [ 18.5],
       [  6.4],
       [  7.6],
       [  1.6],
       [  8.5],
       [-26.9],
       [ -8.7],
       [ 30.6],
       [ 10. ],
       [  1.1],
       [  5.5],
       [-13.1],
       [-15.7],
       [-32.8],
       [ 12. ],
       [ -9.9],
       [

In [9]:
# ターゲットを表示します
training_data['targets'].round(1)

array([[ -9.8],
       [  9.5],
       [ -7. ],
       [ 17.1],
       [  3.9],
       [ 22.5],
       [  1.7],
       [-10.1],
       [ 20. ],
       [-10.1],
       [ 34.2],
       [  5.6],
       [-28. ],
       [-28.5],
       [ -8.4],
       [ 18.1],
       [ 28. ],
       [ 15. ],
       [-15.4],
       [-20.9],
       [  9.1],
       [-19.5],
       [ 14.3],
       [ 27.1],
       [ 22.1],
       [ -1.2],
       [ -8.3],
       [ 28.4],
       [  1. ],
       [-13.5],
       [ 13.4],
       [ 11.4],
       [ -0.3],
       [ 26. ],
       [  0.9],
       [  5.8],
       [ -5.8],
       [ 18.1],
       [ 12.8],
       [  8.7],
       [ -7.5],
       [ 25.6],
       [ -3.3],
       [ 11.3],
       [  7.9],
       [ 12.5],
       [ 19.7],
       [  6.8],
       [  7.4],
       [  1.4],
       [  7.7],
       [-28.1],
       [ -7.9],
       [ 31.7],
       [ 10.3],
       [  1.2],
       [  4.7],
       [-12.6],
       [-16.6],
       [-33.6],
       [ 11.8],
       [-10.6],
       [

## 散布図の作成

In [1]:
# 散布図を表示していきます
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()


NameError: name 'plt' is not defined