In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[4.7423e+30, 4.7393e+30, 9.5461e-01],
        [4.4377e+27, 1.7975e+19, 4.6894e+27],
        [7.9463e+08, 3.2604e-12, 2.6209e+20],
        [4.1641e+12, 1.9434e-19, 3.0881e+29],
        [6.3828e+28, 1.4603e-19, 7.7179e+28]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8739, 0.9310, 0.5443],
        [0.1056, 0.7853, 0.2765],
        [0.5415, 0.0848, 0.0637],
        [0.8406, 0.5549, 0.5809],
        [0.2029, 0.4903, 0.1714]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)

In [5]:
torch.tensor([1,23,3])

tensor([ 1, 23,  3])

In [6]:
x  = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.5282,  0.1530,  1.2117],
        [ 0.6497,  1.2236, -0.2515],
        [ 0.7041,  0.1869,  1.1890],
        [ 1.2036,  0.8442, -0.1032],
        [-0.9516,  0.6869, -1.6793]])


In [9]:
x = torch.arange(0,19,2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [11]:
x = torch.linspace(0,3,4)
print(x)

tensor([0., 1., 2., 3.])


In [12]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [13]:
x = torch.tensor([5,6,7],dtype=torch.int)

In [14]:
print(x.dtype)

torch.int32


In [15]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [16]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [17]:
x.dtype

torch.float32

In [18]:
x.size()

torch.Size([2, 3])

In [20]:
x.shape

torch.Size([2, 3])

In [24]:
x = torch.rand(5,3)
print(x)
y = torch.rand(5,3)
print(y)

tensor([[0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])
tensor([[0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])


In [25]:
print(x + y)

tensor([[1.2215, 0.3201, 1.1121],
        [0.8458, 1.6568, 1.3248],
        [1.4724, 0.9787, 0.1488],
        [0.6403, 0.3224, 1.3567],
        [1.0068, 1.5687, 0.6376]])


In [26]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[1.2215, 0.3201, 1.1121],
        [0.8458, 1.6568, 1.3248],
        [1.4724, 0.9787, 0.1488],
        [0.6403, 0.3224, 1.3567],
        [1.0068, 1.5687, 0.6376]])


In [27]:
y.add_(x)
print(y)

tensor([[1.2215, 0.3201, 1.1121],
        [0.8458, 1.6568, 1.3248],
        [1.4724, 0.9787, 0.1488],
        [0.6403, 0.3224, 1.3567],
        [1.0068, 1.5687, 0.6376]])


In [28]:
print(y[:,1])

tensor([0.3201, 1.6568, 0.9787, 0.3224, 1.5687])


In [29]:
print(y[0,:])

tensor([1.2215, 0.3201, 1.1121])


In [30]:
print(y[2:,1:])

tensor([[0.9787, 0.1488],
        [0.3224, 1.3567],
        [1.5687, 0.6376]])


In [31]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3090])
-0.30899786949157715


In [33]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [34]:
b = a.numpy()
print(b)

[1. 1. 1.]


In [35]:
a.add_(3)
print(a)
print(b)

tensor([4., 4., 4.])
[4. 4. 4.]


In [36]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [37]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1.], dtype=torch.float64)


In [38]:
a = torch.arange(1,4,1,dtype=torch.float)

In [39]:
print(a)

tensor([1., 2., 3.])


In [40]:
a.mean()

tensor(2.)

In [41]:
a.sum()

tensor(6.)

In [42]:
print(a.max())

tensor(3.)


In [43]:
print(a.min())

tensor(1.)


In [44]:
a = torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [45]:
print(torch.add(a,b).sum())

tensor(21.)


In [46]:
import math
a = torch.tensor([math.radians(30), math.radians(60), math.radians(90)])

In [47]:
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [48]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float)

In [49]:
torch.mm(a,b)

tensor([[22., 28.],
        [49., 64.]])

In [50]:
print(a@b)

tensor([[22., 28.],
        [49., 64.]])


In [55]:
x = torch.ones(2,2,requires_grad = True)

In [56]:
y = x + 2

In [57]:
z = (y**2).mean()

In [58]:
z.backward()
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])
